import "@/styles/globals.css"
import Footer from "@/components/Footer"
import Navbar from "@/components/Navbar"

export const metadata = {
  title: 'DZ Web Agency',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/260af2b2e0.js" crossorigin="anonymous"></script>
      </head>
      <body>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
